spring:
       application:
         name: spring-test-web

springdoc:
 api-docs:
   enabled: true
   path: /v3/api-docs
 swagger-ui:
   enabled: true
   path: /swagger-ui.html
   operations-sorter: alpha
   tags-sorter: alpha
   try-it-out-enabled: true
   filter: true
   display-request-duration: true
 default-flat-param-object: true
 packages-to-scan: org.example.springtestweb.controller
 group-configs:
   - group: "default"
     paths-to-match: "/**"
     packages-to-scan: org.example.springtestweb.controller
 model-and-view-allowed: true

server:
  port: 8080
